### ISSUE TITLE
Added Docker and GitHub Action Support

### ISSUE THREAD

**Issue by BRAVO68WEB** [b3h3m0th/britta_discord-music-bot#5]
I have added Supported for GitHub actions and Docker for testing every time we push the code to GitHub Bot's Build Status

This i forgot to a ```git checkout``` before I push to GitHub so the changes were pushed to ```master``` branch only.

Don't Worry I haven't changed anything in Bots Source Code

Pls Delete both ```workflow-setup``` and ```feature``` branch

**Comment by b3h3m0th** [comment]
Removed the branches 👍
